name: Question
description: Ask a question about the project.
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please include as much detail as you can.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you want to know?
      placeholder: How do I ...?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant background or setup.
      placeholder: I am using ...
    validations:
      required: false
  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: Include commands, steps, or attempts.
    validations:
      required: false
